server:
  port: 8040

spring:
  application:
    # 服务之间的调用一般用这个名称
    name: spring-cloud-feign

eureka:
  client:
    serviceUrl:
      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://localhost:8010/eureka/

feign:
  hystrix:
    # Feign自带断路器,在D版本之后,没有默认打开,需要配置
    enabled: true