server:
  port: 8020
#  servlet:
#    context-path: /SpringCloudEurekaClient

spring:
  application:
    # 服务之间的调用一般用这个名称
    name: spring-cloud-client

eureka:
  client:
    serviceUrl:
      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://localhost:8010/eureka/